CTST-210: Implementation of atomic operations
Do translation only when SYCL has corressponding API, that is:
  1. 1-to-1 mapping integer atomic APIs
  2. atomicInc and atomicDec are not supported
  3. Simulate float and double related APIs with available integer APIs
  4. Following two APIs related to __half and __half2 are not supported:
     __half atomicAdd(__half* addr, __half val)
     __half2 atomicAdd(__half2* addr, __half2 val)

NOTE: For 64bit integers atomic operations, if underlaying OpenCL
      runtime missing required extensions (cl_khr_int64_base_atomics and
      cl_khr_int64_extended_atomics), SYCL runtime would generate a
      exception: cl::sycl::feature_not_supported

TODO:
  1. Catch unsupported feature exception generation by SYCL runtime
  2. Investigate usages of atomic operations on local address space,
     if this is a siginificant feature, implement it

Change-Id: Ie65124f686c2e3c64d34093a9ed8ffb68de34828
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/166243
Reviewed-by: Wang, Zhiming <zhiming.wang@intel.com>
Tested-by: Zack Chen <pei-chi.chen@intel.com>